### ISSUE TITLE
Restrict this repo to the interface between zinc and a compiler

### ISSUE THREAD

**Issue by lrytz** [scala/compiler-interface#8]
https://github.com/sbt/compiler-interface/blob/develop/compiler-interface/src/main/java/xsbti/compile/ScalaCompiler.java and most of the types it refers to (`Inputs`, `ScalaCompiler`) are not actually an interface between a Scala compiler and zinc, but an interface between Zinc and a build tool.

The two concerns should be separated.

**Comment by jvican** [comment]
Agreed :+1:, this repository should contain only the strictest java APIs required for incremental compilation. I believe it's very important these two APIs are split up because (a) will make the change a lot easier to understand and (b) will make it easier to evolve these APIs from the Zinc side.
